UploadUsingDALExample/HW5/Models/Request.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace HW5.Models
{
    /// <summary>
    /// A change of major/minor/advisor Request object. This object contains the V#, First and Last
    /// name, date submitted, phone number, catalog year, email, and the updated major, minor, and advisor
    /// of the student making the request.
    /// </summary>
    public class Request
    {
        public int ID { get; set; }

        [Display(Name = "V#:"),DisplayFormat(DataFormatString = "{0:D8}"), Required]
        public int VNo { get; set; }

        [Display(Name = "Last Name:"), Required]
        public string LastName { get; set; }

        [Display(Name = "First Name:"), Required]
        public string FirstName { get; set; }

        [Display(Name = "Date:"), DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}"), Required]
        public DateTime Date { get; set; }

        [Display(Name = "Phone Number:"),DisplayFormat(DataFormatString = "{0:###-###-####}"),Required]
        public long PhoneNumber { get; set; }

        [Display(Name = "Catalog Year:"),Required]
        public string CatalogYear { get; set; }

        [Display(Name = "Email:"), Required]
        public string Email { get; set; }

        [Display(Name = "Major:"), Required]
        public string Major { get; set; }

        [Display(Name = "Minor:"), Required]
        public string Minor { get; set; }

        [Display(Name = "Advisor:"), Required]
        public string Advisor { get; set; }

        public override string ToString()
        {
            return $"{base.ToString()}; VNo = {"V" + VNo} {LastName} {FirstName} {Date} {PhoneNumber} {CatalogYear} {Email} {Major} {Minor} {Advisor}";
        }
    }
}

UploadUsingDALExample/HW5/Controllers/HomeController.cs
using System.Web.Mvc;

namespace HW5.Controllers
{
    public class HomeController : Controller
    {
        /// <summary>
        /// GET: Home
        /// Gets the View for the home page of HW5
        /// </summary>
        /// <returns>The View object for Home/Index</returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

UploadUsingDALExample/HW5/Controllers/RequestController.cs
using HW5.DAL;
using HW5.Models;
using System.Linq;
using System.Web.Mvc;

namespace HW5.Controllers
{
    public class RequestController : Controller
    {
        private RequestContext db = new RequestContext();


        /// <summary>
        /// GET: Request/Index
        /// Displays all of the current change of major requests.
        /// </summary>
        /// <returns>The View object for Request/Index</returns>
        public ActionResult Index()
        {
            return View(db.Requests.ToList());
        }

        /// <summary>
        /// GET: Request/Create
        /// Gets the create form page for creating a new change of major request
        /// </summary>
        /// <returns>The View object for Request/Create</returns>
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// POST: Request/Create
        /// Validates and Posts the new request object input by the user.
        /// </summary>
        /// <param name="request">The new Request object created by user input</param>
        /// <returns>If successful, a redirect view object to Request/Index, otherwise 
        /// a view object for Request/Create with previous inputs still populated</returns>
        [HttpPost]
        public ActionResult Create(Request request)
        {
            if(ModelState.IsValid)
            {
                db.Requests.Add(request);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(request);
        }
    }
}

UploadUsingDALExample/HW5/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div>
    <img src="~/Content/pictures/Engineering_Hero.png" class="img-fluid" alt="Responsive image">
      
</div>


<h2>Welcome to the Update your Major Form</h2>

<div>
    @Html.ActionLink("Update/Change Form", "Create", "Request", new { area = "" }, new { @class = "navbar-brand" })
    @Html.ActionLink("View Change Requests", "Index", "Request", new { area = "" }, new { @class = "navbar-brand" })
</div>

    <style>
        img-fluid {
            background-image: url("~/Content/pictures/Engineering_Hero.png");
            
            
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
        }

        
    </style>

UploadUsingDALExample/HW5/Views/Request/Create.cshtml
@model HW5.Models.Request

@{
    ViewBag.Title = "Create";
}


@Html.ActionLink("Update/Change Form", "Create", "Request", new { area = "" }, new { @class = "navbar-brand" })
@Html.ActionLink("View Change Requests", "Index", "Request", new { area = "" }, new { @class = "navbar-brand" })

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

        <div class="form-group">
            <!-- V# -->
            
        </div>
            <!-- Date -->
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-lg-3" })
            <div class="col-lg-9">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @placeholder = "mm/dd/yyyy" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
            <div class="form-group">
                <!-- Last Name -->
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-lg-3" })
                <div class="col-lg-9">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>


           <div class="form-group"><!-- First Name -->
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-lg-3" })
                <div class="col-lg-9">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>
        
        <div class="form-group">
            <!-- Major -->
            @Html.LabelFor(model => model.Major, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Major, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Major, "", new { @class = "text-danger" })
        </div>

            <div class="form-group">
                <!-- Phone Number -->
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", @placeholder = "5551234567", @min = "1110000000", @max = "9999999999", @maxlength = "10" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <!-- Email -->
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "something@myemail.com" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>
    <div>
            <div class="form-group">
                <!-- Minor -->
                @Html.LabelFor(model => model.Minor, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.Minor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Minor, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
            <div class="form-group">
                <!-- Advisor -->
                @Html.LabelFor(model => model.Advisor, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.Advisor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Advisor, "", new { @class = "text-danger" })
                </div>
        </div>

            <div class="form-group">
                <!-- Catalog Year -->
                @Html.LabelFor(model => model.CatalogYear, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.DropDownListFor(model => model.CatalogYear, new SelectList(new string[] { "2010-11", "2011-12", "2012-13", "2013-14", "2014-15", "2015-16", "2016-17" }), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CatalogYear, "", new { @class = "text-danger" })
                </div>
        </div>


        <div class="form-group">
            <div class="col-lg-9">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div><br />

}
<style>

input[type=text], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    resize: vertical;
}

label {
    padding: 12px 12px 12px 0;
    display: inline-block;
}

input[type=submit] {
    background-color: #4CAF50;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    float: right;
}

input[type=submit]:hover {
    background-color: #45a049;
}

.container {
    border-radius: 5px;
    background-color: #ADD8E6;
    padding: 20px;
}

.col-25 {
    float: left;
    width: 25%;
    margin-top: 6px;
}

.col-75 {
    float: left;
    width: 75%;
    margin-top: 6px;
}

/* Clear floats after the columns */
.row:after {
    content: "";
    display: table;
    clear: both;
}
</style>

UploadUsingDALExample/HW5/Views/Request/Index.cshtml
@model IEnumerable<HW5.Models.Request>

@{
    ViewBag.Title = "Index";
}

@Html.ActionLink("Update/Change Form", "Create", "Request", new { area = "" }, new { @class = "navbar-brand" })
@Html.ActionLink("View Change Requests", "Index", "Request", new { area = "" }, new { @class = "navbar-brand" })

<center><h2>Western Oregon University - Change/Update forms</h2></center>

<!-- Table to list all current change of major requests -->
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CatalogYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Major)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Minor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Advisor)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
       
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CatalogYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Major)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Minor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Advisor)
        </td>
    </tr>
}

</table>

UploadUsingDALExample/HW5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Update your School Information Form</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>

   

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


    


    
        <div class="container body-content">
            @RenderBody()
            <hr />

            <p>&copy; @DateTime.Now.Year - Whitney Meulink</p>

        </div>
 
</body>
</html>